# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy go.mod and go.sum from root
COPY go.mod go.sum ./
RUN go mod download

# Copy backend source code
COPY backend ./backend

# Copy third_party folder
COPY third_party ./third_party

# Build the binary
WORKDIR /app/backend
RUN go build -o server .

# Runtime stage
FROM alpine:3.19
WORKDIR /root/
COPY --from=builder /app/backend/server .
EXPOSE 50051 8080
CMD ["./server"]
