services:
  # gRPC server
  grpc-server:
    build:
      context: .
      dockerfile: backend/dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - mysql-db
    networks:
      - app-network

  # gRPC client
  grpc-client:
    build:
      context: .
      dockerfile: client/dockerfile
    depends_on:
      - grpc-server
    environment:
      GRPC_SERVER_ADDRESS: grpc-server:50051
    networks:
      - app-network

  # MySQL database
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: employee_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

# Persistent database volume
volumes:
  db-data:

# Custom bridge network
networks:
  app-network:
    driver: bridge
