apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ravithej12/employee-backend:latest
          ports:
            - containerPort: 50051
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service.employee-app.svc.cluster.local:27017/employee_db"