apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: employee-app
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None # headless service (useful for stateful apps)
