FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY backend ./backend
COPY third_party ./third_party

WORKDIR /app/backend

RUN go build -o server main.go server.go

FROM alpine:3.19
WORKDIR /root/
COPY --from=builder /app/backend/server .

EXPOSE 8080 9090
CMD ["./server"]
