# Stage 1: Builder
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Install protoc + plugins
RUN apk add --no-cache git protobuf protobuf-dev build-base \
    && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest \
    && go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest \
    && go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

ENV PATH="$PATH:/go/bin"

# Copy all project files to the container
COPY . .

# Change working directory to backend
WORKDIR /app/backend

# Download go modules
RUN go mod download

# Generate proto code
RUN protoc -I . -I ../third_party/googleapis \
    --go_out=pb --go-grpc_out=pb \
    --grpc-gateway_out=pb \
    employee.proto

# Build server binary
RUN go build -o /app/server .

# Stage 2: Final image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 50051 8080
CMD ["./server"]
