apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: employee-app
spec:
  selector:
    app: backend
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: rest
      port: 8080
      targetPort: 8080
  type: NodePort # or LoadBalancer if using cloud
